spring:
  application:
    name: demo
  
  datasource:
    url: jdbc:postgresql://postgres:5432/warehouse_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      
server:
  port: 8080
  address: 0.0.0.0